version: "3.9"

services:
  backend:
    build: ./backend
    container_name: rss_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/rss_urls.txt:/app/rss_urls.txt
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  gateway:
    build: ./gateway
    container_name: rss_gateway
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  frontend:
    image: nginx:alpine
    container_name: rss_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
